### ISSUE TITLE
Documentation for reviver row and col parameters

### ISSUE THREAD

**Issue by kanef** [vanillaes/csv-es#15]
`README.md` documents order of `reviver` arguments as
```
reviver(value, col, row)
```
but implementation seems to pass `value, row, col`, at least for `CSV.parse`.

Also, documentation doesn't say whether `row` and `col` are 1-based or 0-based.  Seems to be 1.

**Comment by evanplaice** [comment]
Good catch 👍. Thank you for taking the time to file an issue.

I must have glanced at that a dozen times without noticing the mistake.

It's a typo in the docs. It should be row first, col second. Both values are 1-based.

The same correction needs to be made for the strigify => replacer argument.

If you'd like to like credit for the fix, you're more than welcome to submit a PR. Otherwise, I'll take care of it in a few hours.

**Comment by evanplaice** [comment]
Fixed in [v2.0.2](https://github.com/vanillaes/csv-es/releases/tag/v2.0.2)
